### ISSUE TITLE
对C++以及Linux系统编程的一点请教

### ISSUE THREAD

**Issue by 11days** [Toby-Fish/Understanding_UnixLinux_Programming#2]
想请教下前辈，现在从事的是C++后台，服务器，游戏服务器，客户端，存储，Linux系统编程，Go后端.....哪一个方向嘞，想请教下接下来的学习路径🌙，如果有幸，这条 issue 能被看到的话....
大二还有4个月结束。。。打算大三上8月底开始海投，，以下是一点个人信息（可以有偿咨询）

1，牛客：https://www.nowcoder.com/users/291655779
2，个人情况（写于24年3月10）：https://www.v2ex.com/t/1022283#reply67
3，简历
![Uploading 大二实习简历.png…]()

4，个人博客（CSDN）：https://cppreference.blog.csdn.net/

**Comment by Toby-Fish** [comment]
刘同学你好，我看了你的简历、个人情况和部分博客，感觉你学习非常认真，考虑问题挺长远的，很优秀啊。
感谢你纠正我仓库代码bug，向我咨询学习路径更是让我受宠若惊。我只是茫茫计科学子里平凡的一员，回顾自己的求职求学之路也是踩坑众多，你简历中展示的不少技术栈我也并不熟悉，恕我实在没有能力对你进行任何指导。
不过我可以分享一下自己的一些经历和感受，也许能给你提供一些参考和启发。
我本科就读于四川大学计算机科学与技术系。
大一沉迷游戏，学习一塌糊涂，大二醒悟，开始发奋，自知与保研无缘，又不想考研，遂打算毕业直接就业，计划大三找大厂实习，靠实习转正留下工作，早点步入社会成为996打工人。
大二大三看了不少书，刷了不少题，最终大三暑假投实习时拿了字节跳动网络部门研发岗offer，实习了近五个月，终因为没能很好适应工作内容与工作强度，最终选择离开。自那以后我对大厂996非常抵触，对未来感到迷茫，在与朋友家人沟通后选择考研，最终上岸兰州大学，做人工智能方向工作。
我进字节实习完全靠的基本功。我在本科学习阶段并没有有意识地向着某个具体方向（如有cpp后台或是游戏客户端）学习对应方向特定技术栈（如计算机图形学或Linux服务器）。我当时坚信基本功过硬才是硬道理，大量的时间花在巩固数据结构与算法、操作系统、计算机网络等基础核心课程知识与cpp语言学习掌握、力扣刷题等基本功的强化。其实现在回看，当初的想法是不太成熟的，光有基本功能选的岗位范围太窄，如果打算毕业直接就业，我建议尽早了解不同岗位的工作内与所涉及技术栈，结合自身条件自我审视后选择一至两个方向，针对性地根据岗位需求完善自己的技术栈。
我的一些小小个人经验是，可以在腾讯阿里等大厂校招网站检索感兴趣的职位，根据大厂职位的招聘要求有针对性的学习。微信小程序offershow是一个还不错的计算机就业薪资查看平台，能给你一些薪资待遇上的参考。
你现在大二，找实习推荐了解下微软针对大一大二学生开放的实习项目，传统大厂的实习，除非特别优秀的，一般不招大二。微软面试难度比国内大厂低很多，非常亲民，我个人比较推荐。
项目方面的话，个人比较推荐操作系统。跟着MIT或是清华的操作系统课，扎扎实实把理论和实验高质量学完，自己手搓一个操作系统，一方面能够极大的加深自身对操作系统的理解，另一方面把这个项目写在简历上也是非常有含金量的，无论哪个哪个方向的面试官都喜欢基础知识的同学。我当初也是尝试手搓了一个操作系统，写在简历里，几乎所有的面试官都对这个项目经历比较感兴趣，几次面试完全围绕操作系统项目问答，因为是自己亲手写的，对答比较流畅，面试官比较满意。
关于cpp语言学习，如果你的确比较喜欢这门语言，觉得学习这门语言本身也是一种乐趣，而不仅仅只是求职所需的工具的话，推荐你看一下候捷老师的cpp课程，github上有资源，候捷老师是cpp领域泰斗，更是cpp教学专家，学完侯老师的课程，对自身cpp能力的提升是巨大的。
限于篇幅，就先写到这里。我是想到什么写什么，写的比较乱，还请见谅。
祝好。



---原始邮件---
发件人: "Liu ***@***.***&gt;
发送时间: 2024年5月10日(周五) 晚上11:10
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Toby-Fish/Understanding_UnixLinux_Programming] 对C++以及Linux系统编程的一点请教 (Issue #2)




 
想请教下前辈，现在从事的是C++后台，服务器，游戏服务器，客户端，存储，Linux系统编程，Go后端.....哪一个方向嘞，想请教下接下来的学习路径🌙，如果有幸，这条 issue 能被看到的话....
 大二还有4个月结束。。。打算大三上8月底开始海投，，以下是一点个人信息（可以有偿咨询）
 
1，牛客：https://www.nowcoder.com/users/291655779
 2，个人情况（写于24年3月10）：https://www.v2ex.com/t/1022283#reply67
 3，简历
 default.png (view on web)
 4，个人博客（CSDN）：https://cppreference.blog.csdn.net/

**Comment by 11days** [comment]
非常感谢您的回复，没想到时隔3年（看贡献记录，应该是3年没用Github了），还能在 Github 里通过邮件的方式联系到原作者，再次感谢。对未来怎么学，更明确了。而且感觉作者好低调啊，字里行间都是过来人对计算机的深刻感悟，受教了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Toby-Fish/Understanding_UnixLinux_Programming"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月11日(星期六) 上午10:13
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Toby-Fish/Understanding_UnixLinux_Programming] 对C++以及Linux系统编程的一点请教 (Issue #2)





 刘同学你好，我看了你的简历、个人情况和部分博客，感觉你学习非常认真，考虑问题挺长远的，很优秀啊。 
 感谢你纠正我仓库代码bug，向我咨询学习路径更是让我受宠若惊。我只是茫茫计科学子里平凡的一员，回顾自己的求职求学之路也是踩坑众多，你简历中展示的不少技术栈我也并不熟悉，恕我实在没有能力对你进行任何指导。 
 不过我可以分享一下自己的一些经历和感受，也许能给你提供一些参考和启发。 
 我本科就读于四川大学计算机科学与技术系。 
 大一沉迷游戏，学习一塌糊涂，大二醒悟，开始发奋，自知与保研无缘，又不想考研，遂打算毕业直接就业，计划大三找大厂实习，靠实习转正留下工作，早点步入社会成为996打工人。 
 大二大三看了不少书，刷了不少题，最终大三暑假投实习时拿了字节跳动网络部门研发岗offer，实习了近五个月，终因为没能很好适应工作内容与工作强度，最终选择离开。自那以后我对大厂996非常抵触，对未来感到迷茫，在与朋友家人沟通后选择考研，最终上岸兰州大学，做人工智能方向工作。 
 我进字节实习完全靠的基本功。我在本科学习阶段并没有有意识地向着某个具体方向（如有cpp后台或是游戏客户端）学习对应方向特定技术栈（如计算机图形学或Linux服务器）。我当时坚信基本功过硬才是硬道理，大量的时间花在巩固数据结构与算法、操作系统、计算机网络等基础核心课程知识与cpp语言学习掌握、力扣刷题等基本功的强化。其实现在回看，当初的想法是不太成熟的，光有基本功能选的岗位范围太窄，如果打算毕业直接就业，我建议尽早了解不同岗位的工作内与所涉及技术栈，结合自身条件自我审视后选择一至两个方向，针对性地根据岗位需求完善自己的技术栈。 
 我的一些小小个人经验是，可以在腾讯阿里等大厂校招网站检索感兴趣的职位，根据大厂职位的招聘要求有针对性的学习。微信小程序offershow是一个还不错的计算机就业薪资查看平台，能给你一些薪资待遇上的参考。 
 你现在大二，找实习推荐了解下微软针对大一大二学生开放的实习项目，传统大厂的实习，除非特别优秀的，一般不招大二。微软面试难度比国内大厂低很多，非常亲民，我个人比较推荐。 
 项目方面的话，个人比较推荐操作系统。跟着MIT或是清华的操作系统课，扎扎实实把理论和实验高质量学完，自己手搓一个操作系统，一方面能够极大的加深自身对操作系统的理解，另一方面把这个项目写在简历上也是非常有含金量的，无论哪个哪个方向的面试官都喜欢基础知识的同学。我当初也是尝试手搓了一个操作系统，写在简历里，几乎所有的面试官都对这个项目经历比较感兴趣，几次面试完全围绕操作系统项目问答，因为是自己亲手写的，对答比较流畅，面试官比较满意。 
 关于cpp语言学习，如果你的确比较喜欢这门语言，觉得学习这门语言本身也是一种乐趣，而不仅仅只是求职所需的工具的话，推荐你看一下候捷老师的cpp课程，github上有资源，候捷老师是cpp领域泰斗，更是cpp教学专家，学完侯老师的课程，对自身cpp能力的提升是巨大的。 
 限于篇幅，就先写到这里。我是想到什么写什么，写的比较乱，还请见谅。 
 祝好。 
 
 
 
 ---原始邮件--- 
 发件人: "Liu ***@***.***&amp;gt; 
 发送时间: 2024年5月10日(周五) 晚上11:10 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;; 
 主题: [Toby-Fish/Understanding_UnixLinux_Programming] 对C++以及Linux系统编程的一点请教 (Issue #2) 
 
 
 
 
   
 想请教下前辈，现在从事的是C++后台，服务器，游戏服务器，客户端，存储，Linux系统编程，Go后端.....哪一个方向嘞，想请教下接下来的学习路径🌙，如果有幸，这条 issue 能被看到的话.... 
  大二还有4个月结束。。。打算大三上8月底开始海投，，以下是一点个人信息（可以有偿咨询） 
   
 1，牛客：https://www.nowcoder.com/users/291655779 
  2，个人情况（写于24年3月10）：https://www.v2ex.com/t/1022283#reply67 
  3，简历 
  default.png (view on web) 
  4，个人博客（CSDN）：https://cppreference.blog.csdn.net/
